apiVersion: v1
kind: Service
metadata:
  name: nginx-init-service
  labels:
    app: nginx-init
spec:
  selector:
    app: nginx-init
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
