apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-app
  labels:
    app: nginx-multitool-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multitool-app
  template:
    metadata:
      labels:
        app: nginx-multitool-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
