apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  labels:
    app: nginx-multitool-app
spec:
  selector:
    app: nginx-multitool-app
  ports:
  - name: nginx-port
    port: 9001
    targetPort: 80
    protocol: TCP
  - name: multitool-port  
    port: 9002
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
