# /home/ilya/project/ansible/ssh_bastion_setup.yml
---
- name: Secure SSH setup for bastion host
  hosts: bastion
  become: yes
  vars:
    ssh_port: 22
    ssh_permit_root_login: "no"
    ssh_password_authentication: "no"
    ssh_pubkey_authentication: "yes"
    ssh_allow_users: "ilya"

    admin_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Add admin SSH key
      ansible.posix.authorized_key:
        user: ilya
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        
    - name: Install openssh-server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Ensure SSH directory exists
      file:
        path: /etc/ssh
        state: directory
        mode: 0755

    - name: Configure SSH daemon
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart SSH

    - name: Ensure admin user exists
      user:
        name: ilya
        groups: sudo
        append: yes
        shell: /bin/bash

    - name: Ensure .ssh directory exists
      file:
        path: /home/ilya/.ssh
        state: directory
        owner: ilya
        group: ilya
        mode: 0700

    - name: Deploy authorized keys
      copy:
        content: "{{ admin_ssh_key }}"
        dest: /home/ilya/.ssh/authorized_keys
        owner: ilya
        group: ilya
        mode: 0600
      when: admin_ssh_key != ""

    - name: Ensure UFW is disabled on bastion
      ufw:
        state: disabled

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted