apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-sc
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/mnt/k8s-storage/sc-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ilyapc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-sc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
  labels:
    app: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Контейнер busybox запущен. Начинаю запись данных через StorageClass..." > /sc-data/data.log
            while true; do
              echo "$(date): Данные от busybox через SC - случайное число: $RANDOM" >> /sc-data/data.log
              sleep 5
            done
        volumeMounts:
        - name: sc-storage
          mountPath: /sc-data
          
      - name: multitool
        image: wbitt/network-multitool:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Контейнер multitool запущен и мониторит файл через StorageClass..." > /proc/1/fd/1
            tail -f /sc-data/data.log
        volumeMounts:
        - name: sc-storage
          mountPath: /sc-data
          
      volumes:
      - name: sc-storage
        persistentVolumeClaim:
          claimName: local-pvc-sc
