# vector-role/tasks/install_vector.yml
---
- name: Install Vector (Ubuntu)
  when: ansible_os_family == "Debian"
  become: yes
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/vector_install
        state: directory
        mode: '0755'

    - name: Download Vector
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/latest/vector-amd64.deb
        dest: /tmp/vector_install/vector.deb
        checksum: sha256:https://packages.timber.io/vector/latest/vector-amd64.deb.sha256

    - name: Install Vector package
      ansible.builtin.apt:
        deb: /tmp/vector_install/vector.deb
      register: install_result
      ignore_errors: yes

    - name: Clean up temporary files
      ansible.builtin.file:
        path: /tmp/vector_install
        state: absent

    - name: Fail if installation failed
      ansible.builtin.fail:
        msg: "Vector installation failed"
      when: install_result is failed

- name: Install Vector (RHEL)
  when: ansible_os_family == "RedHat"
  become: yes
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/vector_install
        state: directory
        mode: '0755'

    - name: Download Vector
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/latest/vector-x86_64.rpm
        dest: /tmp/vector_install/vector.rpm
        checksum: sha256:https://packages.timber.io/vector/latest/vector-x86_64.rpm.sha256

    - name: Install Vector package
      ansible.builtin.yum:
        name: /tmp/vector_install/vector.rpm
        state: present
      register: install_result
      ignore_errors: yes

    - name: Clean up temporary files
      ansible.builtin.file:
        path: /tmp/vector_install
        state: absent

    - name: Fail if installation failed
      ansible.builtin.fail:
        msg: "Vector installation failed"
      when: install_result is failed

- name: Verify Vector installation
  ansible.builtin.command: vector --version
  register: vector_version
  changed_when: false
  become: yes
  ignore_errors: yes

- name: Show Vector version
  ansible.builtin.debug:
    var: vector_version.stdout