FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3 sudo systemd curl ca-certificates gnupg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    echo 'Defaults:root !requiretty' >> /etc/sudoers && \
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

CMD ["sleep", "infinity"]